# -*- coding: utf-8 -*-
"""setup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/imguoyy1115/PINNs/blob/master/main/continuous_time_inference%20(Schrodinger)/Colab/setup.ipynb
"""

!git clone https://github.com/imguoyy1115/PINNs

!wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
!bash Miniconda3-latest-Linux-x86_64.sh -b -p /usr/local/miniconda
!rm Miniconda3-latest-Linux-x86_64.sh

# 写入环境变量（全局生效）
import os
os.environ["PATH"] = "/usr/local/miniconda/bin:" + os.environ["PATH"]

!conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main
!conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r

!conda create -n PINNs python=3.7 -y

!/usr/local/miniconda/bin/conda install -y -n PINNs cudatoolkit=10.0 cudnn=7.6

!/usr/local/miniconda/envs/PINNs/bin/pip list

!/usr/local/miniconda/envs/PINNs/bin/pip install numpy==1.19.5 scipy==1.5.4 matplotlib==3.3.4

!/usr/local/miniconda/envs/PINNs/bin/pip install mkl-service

!/usr/local/miniconda/envs/PINNs/bin/pip install tensorflow-gpu==1.15.0

!/usr/local/miniconda/envs/PINNs/bin/pip uninstall protobuf

!/usr/local/miniconda/envs/PINNs/bin/pip install protobuf==3.20.3

!/usr/local/miniconda/envs/PINNs/bin/pip install matplotlib-inline

!/usr/local/miniconda/envs/PINNs/bin/pip install IPython

!/usr/local/miniconda/envs/PINNs/bin/pip install pyDOE==0.3.8
